name: Build

on:
  push:
    branches: [master]
    paths-ignore: ["**.md"]
  pull_request:
    branches: [master]
    paths-ignore: ["**.md"]

env:
  BUILD_TYPE: Release
  BINARY_DIR: build
  INSTALL_DIR: install
  DEPS_HASH_FILE: deps-hash.txt

jobs:
  build:
    name: CMake Build
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout project.
        uses: actions/checkout@v3

      - name: Install Linux Dependencies
        if: ${{ matrix.os == 'ubuntu-latest'}}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libgtk-3-dev

      - name: Generate Deps Hash
        id: hash
        shell: bash
        run: |
          git submodule --cached status ./deps/ > ${{ env.DEPS_HASH_FILE }}
          echo "${{ hashFiles('deps/**') }}" >> ${{ env.DEPS_HASH_FILE }}
          echo "::set-output name=deps::$(sha256sum ${{ env.DEPS_HASH_FILE }} | cut -d ' ' -f 1)"

      - name: Check Deps Cache
        id: deps-cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.BINARY_DIR }}/deps/install
            !${{ env.BINARY_DIR }}/deps/install/opencv/etc
          key: deps-${{ runner.os }}-${{ steps.hash.outputs.deps }}

      - name: CMake Configure
        run: >-
          cmake -B ${{ env.BINARY_DIR }}
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          -DCMAKE_INSTALL_PREFIX=${{ env.INSTALL_DIR }}
          -DEXPORT_COMPILE_COMMANDS=0
          -DDEPS_SKIP_BUILD=${{ steps.deps-cache.outputs.cache-hit == 'true' }}

      - name: CMake Build
        run: cmake --build ${{ env.BINARY_DIR }} --config ${{ env.BUILD_TYPE }} --target install

      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: AprilTagTrackers-${{ runner.os }}
          path: |
            ${{ env.INSTALL_DIR }}/

      - name: Upload CMake Logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: CMakeLogs-${{ runner.os }}
          path: |
            ${{ env.BINARY_DIR }}/**/CMakeCache.txt
            ${{ env.BINARY_DIR }}/**/CMakeOutput.log
            ${{ env.BINARY_DIR }}/**/CMakeError.log
